# Generated by Django 4.0 on 2022-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.CharField(default='Mathematics', max_length=400),
        ),
    ]
