# Generated by Django 4.0 on 2022-12-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_alter_newuser_country_alter_newuser_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_auth.newuser', verbose_name='user'),
        ),
    ]
