# Generated by Django 4.0 on 2023-01-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0010_alter_newuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
    ]
