# Generated by Django 4.0 on 2022-11-13 13:03

from django.db import migrations, models
import django.db.models.deletion
import pay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=pay.models._generate_payment_id, max_length=100)),
                ('payment_method', models.CharField(choices=[('Ozow', 'Ozow'), ('PayPal', 'PayPal'), ('Braintree', 'Braintree'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('eBucks', 'eBucks'), ('Mobicred', 'Mobicred'), ('Stripe', 'Stripe')], default='CC', max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_paid', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default='Unpaid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_auth.newuser')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'order_payments',
                'managed': True,
            },
        ),
    ]
