# Generated by Django 4.0 on 2022-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Subscribe', 'verbose_name_plural': 'Subscribes'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='last viewed'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_recieved',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recieved'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='date_last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='last viewed'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='date_recieved',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recieved'),
        ),
    ]
