# Generated by Django 4.0 on 2022-12-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_subscribe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='subscribed'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
