# Generated by Django 4.0 on 2022-12-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_subscribe_email_alter_subscribe_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
    ]
