# Generated by Django 4.0 on 2022-11-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_enrolled',
        ),
    ]
