# Generated by Django 4.0 on 2022-11-13 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0005_remove_course_students_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
