# Generated by Django 4.0 on 2022-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_course_options_course_created_course_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='describe',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
