# Generated by Django 4.0 on 2022-11-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose the category for your course.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='describe',
            field=models.CharField(blank=True, help_text='Describe this course in 200 words', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Make it a little bit bigger for cropping', upload_to='course/thumbnails'),
        ),
        migrations.AlterField(
            model_name='course',
            name='motivation',
            field=models.CharField(blank=True, help_text='Motivation e.g Increase your skills in this course', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Enter your course title', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
