# Generated by Django 4.0 on 2022-12-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_course_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students_joined',
            new_name='students_completed',
        ),
    ]
