# Generated by Django 4.0 on 2022-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_alter_course_similar_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_of_class',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
