# Generated by Django 4.0 on 2022-12-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_alter_order_type_of_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'managed': True, 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
