# Generated by Django 4.0 on 2022-12-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(default='modules/default.png', help_text='Make it a little bit bigger for cropping', upload_to='modules/thumbnails'),
        ),
    ]
