# Generated by Django 4.0 on 2022-12-02 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0003_eye_module_file_module_image_module_text_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='students_completed',
            field=models.ManyToManyField(blank=True, related_name='modules_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
