# Generated by Django 4.0 on 2022-12-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
